# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Winny Dhestina
tagline:          'Winny Dhestina'
description:      'Dietitian study log'
url:              http://windhestina.github.io/

author:
  name:           'Winny Dhestina'
  url:            http://windhestina.github.io/

paginate:         2
google_analytics: 'UA-91425204-3'
bing_seo:		  'ECA8D4503D79297E7BB223666F18CAF8'
emailme:          mailto:windhestina@gmail.com

gems:             [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

github:
  repo:           https://github.com/windhestina/windhestina.github.io/

tags:

github_username:  windhestina


